In [15]:
import MDAnalysis as mda
import numpy as np

In [99]:
u = mda.Universe('./CH3OH.pdb')
u.atoms.positions = u.atoms.positions@np.array([[0,0,-1],[0,1,0],[1,0,0]])

In [56]:
c = u.select_atoms('type C')
o = u.select_atoms('type O')
hc = u.select_atoms('type H and around 1.1 group c', c=c)
ho = u.select_atoms('type H and around 1.1 group o', o=o)
u.select_atoms('around 1.07 group c', c=c)

<AtomGroup with 0 atoms>

In [60]:
np.linalg.norm(c.positions-o.positions), np.linalg.norm(hc[:1].positions-c.positions), np.linalg.norm(ho[:1].positions-c.positions)

(1.43, 1.0702944, 1.9701598)

In [78]:
list(u.select_atoms('cyzone 5 -100 200 group c', c=c))

[]

In [100]:
u.atoms.center_of_charge()

NoDataError: AtomGroup.center_of_charge() not available; this requires charges

In [101]:
u.add_TopologyAttr('charge', [0,1,2,3,4,5])
u.atoms.center_of_charge()

array([0.0584    , 0.77593331, 0.68806667])

In [109]:
u.add_TopologyAttr('charge', [0,1,2,3,-4,-5])
u.atoms.center_of_charge(), u.atoms.total_charge()

(array([0.0584    , 0.77593331, 0.68806667]), -3.0)

In [108]:
u.add_TopologyAttr('charge', [0,1,2,3,4,6])
u.atoms.center_of_charge(), u.atoms.total_charge()

(array([0.109375  , 0.79737497, 0.67631251]), 16.0)

In [116]:
hc.shape_parameter(),hc.asphericity(),u.atoms.moment_of_inertia(),

(-0.24999935152562397,
 0.25000021615812534,
 array([[ 2.11990166e+01, -1.76714767e-03, -2.04547707e-03],
        [-1.76714767e-03,  2.04010098e+01, -9.26679534e-01],
        [-2.04547707e-03, -9.26679534e-01,  3.87796270e+00]]))

In [117]:
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD
u = mda.Universe(PSF, DCD)
len(u.trajectory)

E:\anaconda3\Lib\site-packages\MDAnalysis\coordinates\DCD.py:165: DeprecationWarning: DCDReader currently makes independent timesteps by copying self.ts while other readers update self.ts inplace. This behavior will be changed in 3.0 to be the same as other readers. Read more at https://github.com/MDAnalysis/mdanalysis/issues/3889 to learn if this change in behavior might affect you.
  warnings.warn("DCDReader currently makes independent timesteps"


98

In [137]:
u.trajectory.ts, u.trajectory.time

(< Timestep 10 >, 10.999999031120204)

In [138]:
u.trajectory.next()
u.trajectory.ts, u.trajectory.time

(< Timestep 11 >, 11.999998943040223)

In [142]:
u = mda.Universe(PSF, DCD)

u.trajectory[4], u.trajectory[:4], 


(< Timestep 4 >,
 <MDAnalysis.coordinates.base.FrameIteratorSliced at 0x213387af140>)

In [146]:
from MDAnalysis.analysis import rms
protein = u.select_atoms('protein')
rmsd = rms.RMSD(protein, protein).run()
bools = rmsd.results.rmsd.T[-1] < 4
print(bools)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]


In [149]:
rmsd.results

ModuleNotFoundError: No module named 'nglview'

AttributeError: module 'MDAnalysis' has no attribute 'TPR'